import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FlexLayoutModule } from '@angular/flex-layout';
import {
          MatButtonModule,
          MatIconModule,
          MatFormFieldModule,
          MatInputModule,
          MatCardModule,
          MatDatepickerModule,
          MatNativeDateModule,
          MatCheckboxModule,
          MatSidenavModule,
          MatToolbarModule,
          MatListModule,
          MatTabsModule,
          MatSelectModule,
          MatProgressSpinnerModule,
          MatDialogModule,
          MatTableModule,
          MatSortModule,
          MatPaginatorModule,
          MatProgressBarModule,
          MatChipsModule,
          MatMenuModule,
          MatOptionModule
         } from '@angular/material';

@NgModule({
  declarations: [],
  imports: [
    CommonModule,
    MatOptionModule,
    MatButtonModule,
    MatIconModule,
    MatFormFieldModule,
    MatInputModule,
    MatCardModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatCheckboxModule,
    MatSidenavModule,
    MatToolbarModule,
    MatListModule,
    MatTabsModule,
    MatSelectModule,
    MatProgressSpinnerModule,
    MatProgressBarModule,
    MatDialogModule,
    MatTableModule,
    MatSortModule,
    MatPaginatorModule,
    FlexLayoutModule,
    MatChipsModule
  ],
  exports: [
    MatOptionModule,
    MatButtonModule,
    MatIconModule,
    MatFormFieldModule,
    MatInputModule,
    MatCardModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatCheckboxModule,
    MatSidenavModule,
    MatToolbarModule,
    MatListModule,
    MatTabsModule,
    MatSelectModule,
    MatProgressSpinnerModule,
    MatProgressBarModule,
    MatDialogModule,
    MatTableModule,
    MatSortModule,
    MatPaginatorModule,
    FlexLayoutModule,
    MatChipsModule,
    MatMenuModule
  ]
})
export class MaterialModule { }
